### ISSUE TITLE
Data corruption when upgrading from v1.3 to v1.4

### ISSUE THREAD

**Issue by jasny** [ltonetwork/lto-public-chain#78]
![IMG_20210905_210850_837.jpg](https://user-images.githubusercontent.com/100821/132138606-afbba4b8-9b1e-484d-a324-c19575e1f6ac.jpg)

```
public-node-testnet | 2021-09-04 08:50:16,674 ERROR [main] c.l.actor.RootActorSystem$ - Error while initializing actor system ltonetwork
public-node-testnet | org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: 297 missing files; e.g.: /lto/data/000357.sst
public-node-testnet |   at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
public-node-testnet |   at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
public-node-testnet |   at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
public-node-testnet |   at com.ltonetwork.db.package$.openDB(package.scala:23)
public-node-testnet |   at com.ltonetwork.Application.<init>(Application.scala:53)
public-node-testnet |   at com.ltonetwork.Application$.$anonfun$main$3(Application.scala:424)
public-node-testnet |   at com.ltonetwork.Application$.$anonfun$main$3$adapted(Application.scala:398)
public-node-testnet |   at com.ltonetwork.actor.RootActorSystem$.start(RootActorSystem.scala:25)
public-node-testnet |   at com.ltonetwork.Application$.main(Application.scala:398)
public-node-testnet |   at com.ltonetwork.Application.main(Application.scala)
```

Only way to solve it is to sync from genesis.

**Comment by BlackTurtle123** [comment]
Updating from both 1.3.1, 1.3.2 both gives corruption trying now 1.3.0

**Comment by BlackTurtle123** [comment]
> Updating from both 1.3.1, 1.3.2 both gives corruption trying now 1.3.0

Also 1.3.0 gives data corruption, so the corruption is there for EVERY upgrade and for EVERY version.

**Comment by jasny** [comment]
The files used to have the `.ldb` extension, but now the `.sst` extension is expected. The format seems unchanged. After renaming the `.ldb` files to `.sst` file, the issue doesn't occur.

**Comment by jasny** [comment]
LevelDB is downgraded in https://github.com/ltonetwork/lto-public-chain/commit/42361676baf0143cdf6e1735401c774e8a3e60ec
