### ISSUE TITLE
Concurrency issue during shutdown

### ISSUE THREAD

**Issue by jasny** [ltonetwork/lto-public-chain#81]
```
021-09-08 00:06:00,253 INFO  [appender-50] c.w.s.BlockchainUpdaterImpl - New height: 101900
2021-09-08 00:06:00,309 INFO  [metrics-17] c.w.utils.TimeImpl - Shutting down Time
2021-09-08 00:06:00,337 INFO  [shutdownHook2] c.w.Application - HistoryReplier was shutdown successfully
2021-09-08 00:06:00,337 INFO  [shutdownHook2] c.w.Application - Closing REST API
2021-09-08 00:06:00,366 INFO  [shutdownHook2] c.w.n.PeerDatabaseImpl - Saving 5 known peer(s) to peers.dat
2021-09-08 00:06:00,452 INFO  [shutdownHook2] c.w.Application - Stopping network services
2021-09-08 00:06:00,462 INFO  [appender-50] c.w.s.BlockchainUpdaterImpl - New height: 102000
2021-09-08 00:06:04,886 INFO  [shutdownHook2] c.w.Application - Miner was shutdown successfully
2021-09-08 00:06:04,887 INFO  [shutdownHook2] c.w.Application - MicroblockSynchronizer was shutdown successfully
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4709e1dd[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@634ebe6[Wrapped task = monix.reactive.observers.buffers.AbstractBackPressuredBufferedSubscriber$$anon$1@20b6ff8]] rejected from monix.execution.schedulers.SchedulerCompanionImpl$$anon$1@57ce7af0[Shutting down, pool size = 1, active threads = 0, queued tasks = 3, completed tasks = 191636]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:705)
	at monix.execution.schedulers.ExecutorScheduler.executeAsync(ExecutorScheduler.scala:41)
	at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:53)
	at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:47)
	at monix.execution.schedulers.ExecutorScheduler.execute(ExecutorScheduler.scala:34)
	at monix.reactive.observers.buffers.AbstractBackPressuredBufferedSubscriber.pushToConsumer(AbstractBackPressuredBufferedSubscriber.scala:116)
	at monix.reactive.observers.buffers.AbstractBackPressuredBufferedSubscriber.pushComplete(AbstractBackPressuredBufferedSubscriber.scala:101)
	at monix.reactive.observers.buffers.AbstractBackPressuredBufferedSubscriber.onComplete(AbstractBackPressuredBufferedSubscriber.scala:109)
	at monix.reactive.internal.operators.ObserveOnObservable$$anon$2.onComplete(ObserveOnObservable.scala:56)
	at monix.reactive.subjects.PublishSubject.sendOnCompleteOrError(PublishSubject.scala:176)
	at monix.reactive.subjects.PublishSubject.onComplete(PublishSubject.scala:108)
	at monix.reactive.observers.Subscriber$Implementation.onComplete(Subscriber.scala:208)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.signalComplete(SimpleBufferedSubscriber.scala:149)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.fastLoop(SimpleBufferedSubscriber.scala:229)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.run(SimpleBufferedSubscriber.scala:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3c63512b[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@369b3a5b[Wrapped task = monix.reactive.observers.buffers.AbstractBackPressuredBufferedSubscriber$$anon$1@385cc2f8]] rejected from monix.execution.schedulers.SchedulerCompanionImpl$$anon$1@7961c8c3[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 202741]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:705)
	at monix.execution.schedulers.ExecutorScheduler.executeAsync(ExecutorScheduler.scala:41)
	at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:53)
	at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:47)
	at monix.execution.schedulers.ExecutorScheduler.execute(ExecutorScheduler.scala:34)
	at monix.reactive.observers.buffers.AbstractBackPressuredBufferedSubscriber.pushToConsumer(AbstractBackPressuredBufferedSubscriber.scala:116)
	at monix.reactive.observers.buffers.AbstractBackPressuredBufferedSubscriber.pushComplete(AbstractBackPressuredBufferedSubscriber.scala:101)
	at monix.reactive.observers.buffers.AbstractBackPressuredBufferedSubscriber.onComplete(AbstractBackPressuredBufferedSubscriber.scala:109)
	at monix.reactive.internal.operators.ObserveOnObservable$$anon$2.onComplete(ObserveOnObservable.scala:56)
	at monix.reactive.subjects.PublishSubject.sendOnCompleteOrError(PublishSubject.scala:176)
	at monix.reactive.subjects.PublishSubject.onComplete(PublishSubject.scala:108)
	at monix.reactive.observers.Subscriber$Implementation.onComplete(Subscriber.scala:208)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.signalComplete(SimpleBufferedSubscriber.scala:149)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.fastLoop(SimpleBufferedSubscriber.scala:229)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.run(SimpleBufferedSubscriber.scala:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jasny** [comment]
Seems to be fixed by https://github.com/ltonetwork/lto-public-chain/commit/670ac9405951bba041bb2856b82bdc638f8deeb9

Issue should be reopened when this is still experienced.
